apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starboard
  labels:
    app.kubernetes.io/managed-by: starboard
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicationcontrollers
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
