apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: starboard
  labels:
    app.kubernetes.io/managed-by: starboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: starboard
subjects:
  - kind: ServiceAccount
    name: starboard
    namespace: starboard
