apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ciskubebenchreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/managed-by: starboard
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    singular: ciskubebenchreport
    plural: ciskubebenchreports
    kind: CISKubeBenchReport
    listKind: CISKubeBenchReportList
    categories:
      - all
    shortNames:
      - kubebench
  additionalPrinterColumns:
    - JSONPath: .report.scanner.name
      type: string
      name: Scanner
    - JSONPath: .metadata.creationTimestamp
      type: date
      name: Age
    - JSONPath: .report.summary.passCount
      type: integer
      name: Pass
      priority: 1
    - JSONPath: .report.summary.infoCount
      type: integer
      name: Info
      priority: 1
    - JSONPath: .report.summary.warnCount
      type: integer
      name: Warn
      priority: 1
    - JSONPath: .report.summary.failCount
      type: integer
      name: Fail
      priority: 1
