name: Build
on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '12.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout coce
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install npm dependencies and build extension
        run: |
          npm ci
          npm run build
